name: Validate HTML

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
  schedule:
    # Run everyday at 4:30 AM
    - cron: "30 4 * * *"

jobs:
  validate-html:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@master
    - name: Run validate-html
      uses: chabad360/htmlproofer@master
      with:
        directory: "./"
        arguments: "--check_opengraph --check-html"
